### ISSUE TITLE
Fileles build option

### ISSUE THREAD

**Issue by Christer-Ekholm** [likle/cargs#13]
Hi. 

Are you interested following API change?

```c
#ifndef NO_FILE_SUPPORT
CAG_PUBLIC void cag_option_print(const cag_option *options, size_t option_count,
  FILE *destination);
#endif

typedef int(*cag_printer)(void *ctx, const char *fmt, ...);

CAG_PUBLIC void cag_option_print_cb(const cag_option* options, size_t option_count, cag_printer printer, void *ctx);
```

My embedded system does not have file support so I refactored API so that I could use callback to print help texts. Are you interested to receive PR ? I am too lazy to make it if you are not interested to extending API for embedded usage.

**Comment by likle** [comment]
Hi @Christer-Ekholm , sure, that sounds interesting - if it isn't all too ugly/problematic I'll merge it 🙂

**Comment by Christer-Ekholm** [comment]
https://github.com/likle/cargs/pull/14 done
