### ISSUE TITLE
Obsolete non-standard header memory.h?

### ISSUE THREAD

**Issue by piscilus** [likle/cargs#15]
cargs.c includes memory.h which is not a standard library header.

Is there are reason to use memory.h? Limiting the project to the standard headers would increase portability.

I removed the include and successfully built a test project with gcc 11 (Linux) and gcc 13 (Windows).

(libcargs v1.1.0)

**Comment by likle** [comment]
Hi @piscilus ! Thanks for reporting this. You are right. I think that's just a header I never removed. I took care of it in the last commit.
