### ISSUE TITLE
About code style

### ISSUE THREAD

**Issue by xmo0** [likle/cargs#16]
hi @likle,
There are a little suggestions about code style as follows：
1、I notice the maximum line width is 80 in most cases, but some is 100.
2、maybe use a .clang-format file to help people to make sure the code style fits the surrounding code. I notice there **is** a .clang-format file in the repo, but with too few constraints and terms in it.
Forgive me for my poor English. -:p

**Comment by likle** [comment]
Hi @xmo0 !

Thank you for reaching out. Your English might be better than mine! 🙂

1. You are right, it should be 80, if you see something different I'd be happy to take contributions!

2. Yes, there is a clang-format. The rules are based on LLVM and modifies the ones I wanted different. Did you have any specific constraints in mind?

**Comment by xmo0** [comment]
[clang-format.txt](https://github.com/likle/cargs/files/15050461/clang-format.txt)

Here is a .clang-format file which I recently use with C files. Not suit for this repo code style, but has many constrainsts. Just for your information.
"Did you have any specific constraints in mind?" -> Not any.
