### ISSUE TITLE
broken image link at root page

### ISSUE THREAD

**Issue by vb64** [likle/cargs#3]
![image](https://user-images.githubusercontent.com/8738387/114758914-91063a80-9d6e-11eb-8854-e31bcaacdbe9.png)

The project looks nice.

**Comment by likle** [comment]
Hi @vb64 ! Thanks a lot for reporting this! I am having trouble to reproduce this. May I ask what client/browser you are using and which URL you are looking at? does it persist after clearing the cache?

**Comment by vb64** [comment]
url: https://github.com/likle/cargs
client: Google Chrome 89.0.4389.128 (64 bit)
Ctrl+F5, Ctrl+F5, Ctrl+F5 does not fix the problem

Maybe image sizes or format gives this effect.

**Comment by vb64** [comment]
or just replace in README.md

`<img style="width:100%;" src="/banner.png">`

to 

`<img style="width:100%;" src="banner.png">`

**Comment by likle** [comment]
It's strange because I've tested it on a few devices and browsers and it seemed to work. I've made that change you suggested, maybe it works for you now too?

**Comment by vb64** [comment]
Looks like my Google Chrome only problem.

Mozilla and other browsers render the page as planned.

**Comment by likle** [comment]
I understand. Thank you for testing, its really appreciated!
