### ISSUE TITLE
`cag_option_print` not working  in mingw64 (but works in msvc)

### ISSUE THREAD

**Issue by Kamrulhasan12345** [likle/cargs#5]
Hi,
Yesterday I was trying to use cargs. First I tried building with mingw gcc in windows. But everything went ok before testing help command. help command only printed "demonstra...." line and then paused for a second then stopped execution. But I tried doing this in wsl2 and msvc, and they worked perfectly there. Can you figure out the issue?

**Comment by likle** [comment]
Hi @Kamrulhasan12345 , I can not reproduce your issue. Could you provide more information what version of mingw64, gcc etc. you are using and how exactly you are compiling?

**Comment by likle** [comment]
I could have a look but I will need a demo project where it doesn't work. Could you provide that?

**Comment by Kamrulhasan12345** [comment]
I tried reconfiguring vcpkg, but of no use, I even tried with cargs demo project, but not worked, but yes when git cloned and tried the demo file inside that which clones cargs projects by git, everything worked. So it seems to me that either vcpkg cargs package is missing something or its an issue with vcpkg

**Comment by Kamrulhasan12345** [comment]
At last, I installed cargs in my mingw by modifying prefix in cmake_install.cmake file in cargs to /mingw64 and then all cargs header file were installed in mingw64. Then I just wrote gcc main.c -lcargs. and then tried running a.exe -h and that perfectly worked! seems to be an issue vcpkg

**Comment by likle** [comment]
I see, did you set the vcpkg triplet correctly? At least for me it seems to have worked fine following this guide:
https://vcpkg.io/en/docs/users/mingw.html

Although I had to copy the shared library manually, which surely can be fixed in some way.

**Comment by Kamrulhasan12345** [comment]
I did not if I there is x64-mingw-** triplets too! anyways, for some other reasons, I am planning not to vcpkg, and as this issue doesn't link to cargs, so closing it.
