### ISSUE TITLE
Non-option arguments

### ISSUE THREAD

**Issue by markmaker** [likle/cargs#6]
Thank you for this nice project.

Could you please add an example with non-option arguments and how to read them?

I guess the following example is self-explanatory, the `src` and `dst` arguments would be non-option file paths: 

```
filecopy --recursive --overwrite=newer src dst
```
I've tried to understand the source code (quickly), but failed. 

Thank you.

_Mark

**Comment by likle** [comment]
Hi @markmaker , I have been thinking for a while now to provide an explicit API for that, but for now you can simply do it like this:

```c
 for (param_index = context.index; param_index < argc; ++param_index) {
   printf("additional parameter: %s\n", argv[param_index]);
 }
```

This has to happen after the option loop. I have added the example to the README.md and the example in the demo folder as well. Does that help you?

**Comment by likle** [comment]
Also, the parameters will stay in order as they were supplied. So if you want to access them by index:
```c
int non_option_parameter_count = argc - context.index;
if (non_option_parameter_count == 2) {
  const char *first_non_option_parameter = argv[context.index];
  const char *second_non_option_parameter = argv[context.index + 1];
}
```

**Comment by markmaker** [comment]
Perfect, thanks!
👍
