### ISSUE TITLE
README.md uses CRLF line endings

### ISSUE THREAD

**Issue by davidebeatrici** [likle/cargs#7]
From `rpmbuild`:

```
W: wrong-file-end-of-line-encoding /usr/share/doc/lib64cargs-devel/README.md
```

**Comment by likle** [comment]
Hi @davidebeatrici , Thanks for reporting this! I changed the line endings. Does that help?

Are you building this package yourself or is this from a repository?

**Comment by davidebeatrici** [comment]
Hi @likle, thank you very much for the quick fix!

I packaged your library for OpenMandriva: https://github.com/OpenMandrivaAssociation/cargs

Please note that ideally LF should be used for the entire repository.

**Comment by likle** [comment]
> I packaged your library for OpenMandriva: https://github.com/OpenMandrivaAssociation/cargs

Thank you very much!

> Please note that ideally LF should be used for the entire repository.

Done. Hope it helps!

**Comment by davidebeatrici** [comment]
Awesome!

Could you do the same for cwalk, please? I packaged it too, of course: https://github.com/OpenMandrivaAssociation/cwalk
